### ISSUE TITLE
能否加入 server 端 API 的文档 

### ISSUE THREAD

**Issue by lslzl3000** [devsapp/fc-llm-api#2]
想直接在代码中调用类似 openai chat/complation 的 API，但不知道后端 server 的具体 API 文档，能否加入相关介绍

**Comment by lslzl3000** [comment]
否则很难在实际项目中使用，叫 llm-api 缺只能通过 一个 client 页面进行调试，希望有对应的详细 api 文档

**Comment by lslzl3000** [comment]
看发送的请求，好像server都用的openai格式的参数，应该是后端都做了api格式的统一？

**Comment by hanxie-crypto** [comment]
请问您用的是fc-llm-api 这个应用模板么？这个模板部署好之后有两个域名， client 和server的各有一个，其中server的部分是对应后端api文档地址
