### ISSUE TITLE
冷启动超时问题

### ISSUE THREAD

**Issue by lslzl3000** [devsapp/fc-llm-api#3]
测试发现，长时间不用后，再次请求 server 的地址，会经常遇到冷启动 fc 120s超时问题 heath check timeout
需要重试很多次才能将服务启动，通常需要在3-5分钟才可以正常启动，请问有什么可以优化的地方？还是必须等待这个冷启动时间？

fc一般正常的应用或函数，冷启动秒级别是可以忍受的，但对于这种llm镜像冷启动需要分钟级别，确实没法使用了，希望有加速或解决办法

**Comment by robinsonnie** [comment]
对于LLM而言，建议使用预留GPU实例。

https://developer.aliyun.com/article/1307460?spm=5176.28261954.J_7341193060.1.43f42fdewvfTyq&scm=20140722.S_community@@%E6%96%87%E7%AB%A0@@1307460._.ID_1307460-RL_%E9%AD%94%E6%90%AD%20%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2-LOC_search~UND~community~UND~item-OR_ser-V_3-P0_0

**Comment by lslzl3000** [comment]
感谢回答，不过这样也失去了 fc 的优势了，而且gpu实例不支持闲置模式，费用有点高呀

**Comment by robinsonnie** [comment]
1. 可以计算一下FC GPU实例和ECS GPU实例的费用，T4比ECS便宜，A10比ECS贵一点；基于FC预留与基于ECS预留，费用上并没有特别大的差异，另外使用FC大大简化的开发体验，减少了运维成本。
2. GPU实例的闲置计费已经开始公测，对比ECS会有较大的费用下降，可通过如下链接进行申请试用：
https://help.aliyun.com/zh/fc/configure-provisioned-instances-and-auto-scaling-rules?spm=a2c4g.11186623.0.i199#31148670584lg
